# Generated by Django 5.0.2 on 2024-04-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='/myApp/static/product/redrose.jpg', upload_to='products'),
        ),
    ]
