# Generated by Django 5.0.2 on 2024-04-28 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_ref',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myApp.product'),
        ),
    ]
